name: update_rmd_files
on:
  push:
    branches:
      - main
      - master

jobs:
  trigger_pull:
    name: trigger_pull
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.RMD }}
    steps:
      - uses: actions/checkout@v2
      - name: update version number
        run: |
            git pull
            awk -F. '{$3++;print > "vignettes/repo_version.txt"}' OFS=. vignettes/repo_version.txt
      - name: Update github
        run: |
          git config --local user.name "dcassol"
          git config --local user.email "danicassol@gmail.com"
          git add -A
          git commit -m "Bot update rmd description files" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Dispatch event SPtemplate_test
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.RMD }}
          repository: 'dcassol/SPtemplate_test'
          event-type: rmd-updated
